version: '3.1'

services:

  db:
    image: postgres:alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eridon_bot:
    container_name: eridon_bot
    image: eridon_bot_image
    build:
      context: bot
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - logigng_data:/home/docker_user/app/log



  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
volumes:
  postgres_data:
  pgadmin_data:
  logigng_data: